# Generated by Django 3.0.6 on 2020-06-24 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAdGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.PositiveIntegerField(default=0, verbose_name='Task id')),
                ('name', models.CharField(blank=True, max_length=63, verbose_name='Group name')),
                ('region', models.CharField(blank=True, max_length=24, verbose_name='Регион')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.BooleanField(blank=True, default=True, verbose_name='Статус')),
                ('records_number', models.PositiveIntegerField(default=0, verbose_name='Количество полученных обьяв')),
                ('main_link', models.TextField(blank=True, verbose_name='стартовая ссылка')),
                ('main_link_param', models.CharField(blank=True, max_length=63, verbose_name='?=параметры ссылки')),
                ('page_idx', models.PositiveIntegerField(default=0, verbose_name='начальная страница')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='Количество страниц')),
            ],
        ),
        migrations.CreateModel(
            name='ParseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=30, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('page_idx', models.PositiveIntegerField(default=0, verbose_name='начальная страница')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='Количество страниц')),
                ('db_updated', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, verbose_name='Статус')),
                ('title', models.TextField(verbose_name='Заголовок объявления')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('price_currency', models.CharField(blank=True, max_length=3, verbose_name='Валюта')),
                ('ad_link', models.TextField(unique=True, verbose_name='Ссылка на объявление')),
                ('img_link', models.TextField(blank=True, verbose_name='Ссылка на изображение')),
                ('transmission', models.CharField(blank=True, max_length=24, verbose_name='Тип трансмиссии')),
                ('production_date', models.PositiveIntegerField(default=0, verbose_name='Дата выпуска')),
                ('fuel_type', models.CharField(blank=True, max_length=24, verbose_name='Тип топлива')),
                ('color', models.CharField(blank=True, max_length=24, verbose_name='Цвет кузова')),
                ('brand', models.CharField(blank=True, max_length=24, verbose_name='Brand name')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parserapp1.CarAdGroup')),
            ],
        ),
    ]
