# Generated by Django 3.0.6 on 2020-06-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carads',
            name='region_idx',
            field=models.PositiveIntegerField(default=0, verbose_name='индекс региона URLS'),
        ),
    ]
